/*
  ARTIGOS DA BOANERGES
  Para publicar um artigo, copie um bloco { ... } abaixo, cole no topo da lista e edite.
  - slug: identificador curto, sem espaços nem acentos (vira o link: /artigo?a=slug)
  - data: "AAAA-MM-DD"
  - corpo: lista de blocos, em ordem:
      "Texto"                         → parágrafo
      "Texto com *itálico*"           → asteriscos deixam o trecho em itálico
      { titulo: "..." }               → subtítulo
      { citacao: "..." }              → citação em destaque
      { nota: "..." }                 → nota pequena em itálico (agradecimentos, avisos)
      { imagem: "assets/x.jpg", legenda: "..." } → imagem (legenda opcional)
      { imagem: "...", legenda: "...", tamanho: "pequena" } → imagem menor, centralizada (bom p/ capas de livro e retratos)
  - conto: true → parágrafos com recuo e sem espaço entre eles (para contos e ficção)
  - en: { titulo, resumo, corpo } → versão em inglês (mostra o seletor PT / EN)
  - processo: "link" → mostra "acompanhe o processo criativo" abaixo do subtítulo
  - rascunho: true → esconde o artigo do site
*/
window.BOANERGES_ARTIGOS = [
  {
    slug: "o-mundo-se-lembra",
    titulo: "O Mundo se Lembra",
    resumo: "Uma pequena estória por Israel Subira",
    data: "2026-10-09",
    autor: "Israel Subira",
    conto: true,
    processo: "https://www.instagram.com/stories/highlights/17937901596391987/",
    en: {
      titulo: "The World Remembers",
      resumo: "A Short Story by Israel Subira",
      corpo: [
        { nota: "Special thanks to Renan Butkeraites, Italo Pacheco, Dhomini Martins, Yrwin Gomes, and Rony for the suggestions." },
        "Another line, another thread. Hours disappeared and days sort of blended into one when Old Man Rorik was sewing. The constant spin of the wheel often robbed him of his attention. It gave him an unsettling feeling that time was… fleeting. Perhaps it was not so much the wheel as it was old age; he could not keep the treadle going for too long on account of his bad knee. Regardless, it did not take much to rob Old Man Rorik of his attention. Not that sewing was not an attention-worthy endeavor, but it was rather monotonous by nature. It was as good a job as any for a man his age, and the pay was sufficient for him and his lady to live comfortably, in his village, at least.",
        "It was not a teeming hub of adventurers. There was no major guild nor the most buzzing of taverns; what it had was plenty of older folk, such as themselves. The village was not too far away from one of the great cities of the province. Most of the commercial activity that happened in the village was on account of adventurers who came looking for services at a discounted price. It was not how Rorik had pictured his later days. Watching adventurers come and go, dropping whatever was damaged in one quest, be repaired by his own hands, only to be taken to another, while he himself was unable to do much of valor these days felt like a thorn in his side.",
        "The old man sighed. *Another one done*, he thought, as he cut the thread from the wheel and finished winding it onto the spool. He took a good look outside, the village calm as only a handful of people walked the stone path.",
        "*Is it time for tea yet?*",
        "Rorik was a bit of a tea enthusiast, but he was very systematic, ritually so. He allowed himself two tea breaks in the day, every single day of course. But one was in the breaking of his fast, and the other was at the end of his workday, together with his wife.",
        "However, the sun was still too high to call it a day.",
        "“Ughh,” he muttered, as he stretched his back.",
        "*I have time for one more.*",
        "He reached for a cloak folded atop his station, and there was some parchment pinned to it. In it there were instructions he had left himself earlier of what to do with the order.",
        "He read the parchment; in his own handwriting, it said, “Sew with waxed linen thread, the green.” He nodded slightly, remembering why he had been spinning the flax in the first place: this cloak would take the last of his green.",
        "The cloak was a fine one; it was dark green and it had some adornments in its edges, held together on the top by a bronze pin from the ranger’s guild. This must have been a recruit, however, embarrassed to turn the cloak in for repairs with the quartermaster of his guild.",
        "“What happened here?” he whispered, as he unfolded the cloak and let it hang from his hands, spotting the hole on it right away.",
        "It looked as if an arrow had gone straight through it; Rorik inspected the damage a little closer. It looked as if it had been caused by a crude arrowhead.",
        "*Goblins, surely.*",
        "He smirked, imagining exactly how things must have gone down. That was one way of ruining a perfect cloak. *But again, better a damaged cloak than taking an arrow to the knee*, he thought, as his hands intuitively rested atop his right knee. He then grunted in dismissal and reached for one of the drawers in his sewing table. He went through a couple of labeled tins and then his hand reached the end of the drawer.",
        "He closed it in frustration and tried another. Nothing.",
        "He warmed up his throat with a slight cough and then broke the quiet of the household.",
        "“Maeve!”",
        "There was a little delay, as if his wife had also coughed a warmup elsewhere in the house.",
        "“Whaaaat?” the voice hollered from downstairs.",
        "“Have you seen the beeswax!?”",
        "“The what!?”",
        "He grunted and got up, moving slowly towards the door with a subtle limp. He opened the door entirely and shouted again, facing down the stairs.",
        "“The beeswax!”",
        "There was a beat of silence.",
        "“I brought it downstairs to seal a letter.”",
        "Rorik sighed in frustration. Maeve knew how he felt about her grabbing things in his study and not returning them to their proper places.",
        "“How about you bring it back here then!?”",
        "The answer came swiftly.",
        "“Ye come and get it, ye old fart!”",
        "Rorik chortled. Maeve had always been very… intense. She did not think twice before saying whatever she was thinking, but she somehow managed to be endearing even in her bluntness. Rorik knew his breath would be wasted in debate; Maeve was stubborn after all.",
        "So, he began the descent downstairs; it was a short journey. Though it was more challenging for him now than he’d care to admit.",
        "*How sloppy do you have to be to get hit by a goblin’s arrow?* he thought as he took the first step down. *I would never have let that happen, not in my prime.* His aching knee almost begged to disagree, but to be hit by an elven archer that belonged to a death cult was completely different.",
        "He took a look to his right side, where a gryphon’s beak attached to a wooden plate hung in the stairwell, trophies of journeys long gone.",
        "He could not help but remember the time he and his mates brought the fierce creature down. It had been attacking a village far in the West, endangering traders and children. He and his fellows only happened to be passing by when they heard the rumors and offered to help.",
        "Rorik still remembered the scoff the village headman let out when they said they would handle the creature, and the shock in the face of the same when they strolled back into the village with the creature’s head. Rorik still had a scar or two from that encounter. However, his smile quickly faded. For when he returned to the village a couple months later, no one knew who he was.",
        "He struggled down another step as he glanced at the broken shield hung in two pieces on the left side of the wall, another one of his relics. He had faced a hulking troll by himself and lived. Not without scars of course, but it was a duel of legend, at least in his mind.",
        "But there were no tales or songs about it either.",
        "That final step hurt more than the previous ones, as if he had somehow gotten heavier with emotion as he descended. That was Rorik’s pain. He had always dreamed of becoming a hero, like the ones of legends and songs he listened to growing up. But no one remembered him for any of his adventures. *I suppose felling gryphons was not as impressive as slaying dragons, and dueling trolls was not as impressive as bringing giants down.* There had been others who became heroes during his time, but Rorik had not been one of them. He was known as naught but a tailor from a small village now. He dragged a step forward towards a window, checking the sun once more. Obviously, it barely had any time to descend from the last time he checked, so it was not yet teatime. Nothing but his own systematic ways prevented him from drinking it at another time, but he, too, was stubborn. He walked by a piece of parchment nailed to the wall, a drawing in charcoal from his granddaughter, but he paid it no mind as he walked into the kitchen.",
        "He was after the beeswax, but it was almost as if his own steps deceived him and led him to the pantry. But it was not yet teatime. He stood before the pantry for a moment though, admiring his own collection of herbs. He took the smell in all at once, but once they came in, he could differentiate the crisp pine tone from the rosemary, the earthy musk from the sage, and the warm spice of thyme. He began to turn away from the pantry, but then eyed a herb encased in a glass jar. He could not help himself. He reached it and lifted the lid, taking in zest and citrus.",
        "*Lemon verbena.*",
        "He closed his eyes in delight, as if the smell alone had appeased some of his longing for his second teatime. He put the herb back. This one was only for special occasions, harder to come across than the other herbs.",
        "And before he could bring himself away from the pantry and after the beeswax, a gentle hand touched his shoulder.",
        "Maeve’s.",
        "She had an earnest smile across her face, though Rorik knew her well enough that half that smile was because she had managed to bring him downstairs instead of taking the climb, but the other half simply said “I love you” without the need for words.",
        "You see, that had been something that made Rorik fall for Maeve back in the day. Or helped, better said, for no one thing is the sole cause of one falling for another. The way that Maeve spoke with her eyes, lips, and shoulders, without even needing to say a word. She was rather playful with her words, always calling her friends names some would deem impolite or making jokes some would find offensive, but all the while her voice was tender and her posture kind.",
        "She stretched her hand with the cake of beeswax, still forcing Rorik to take another step closer to her and grab it from her hand.",
        "“What ye working on?” she asked with a thick accent.",
        "“Ranger’s cloak. Hit by a goblin’s arrow, I’m sure.”",
        "He did not linger too long; he turned around as he made his way to the stairs once more.",
        "“Goblin’s arrow?” she asked once more.",
        "Rorik simply grunted in agreement.",
        "“Sloppy,” she commented as he began fighting his way up the steps one by one.",
        "He chuckled a bit; he had thought the same.",
        "“Ye would never,” she added, with a gentle tone.",
        "It drew a smile from Rorik right away.",
        "“You bet I would never,” he said as he finished his way up.",
        "He let out another grunt as he sat down to resume his work.",
        "He took the hank of green linen from its peg and held a length of it against the cloak; the color was nearly identical. A good eye would be able to tell the minor discrepancy. He frowned and continued. He was sure the quartermaster of the guild could have matched it, but his ranger customer had opted for a simpler craftsman, be it for the embarrassment or the discount.",
        "He trimmed the ragged edges of the hole and laid a scrap of green wool behind it. Then he drew the thread across the cake of wax, once, twice, until it ran stiff and smooth between his fingers, and threaded the needle on the second try, which he counted a small victory. It did not take long before he checked the sun again; it was a little lower, not low enough.",
        "He then patched the hole, bit by bit, thread by thread. He looked outside the window to check the time once more. A neighbor passed and waved from down below. Rorik had his hands busy, so he gave the neighbor a nod instead.",
        "The stitches went in small and close, each one catching the edge of the tear and pulling it down against the patch. Under, over, pull. Under, over, pull. It was not unlike the wheel, in the end. The hands knew the way, and the mind was free to wander wherever it pleased.",
        "The needle crossed the cloth for the last time. The cloak was mended. Rorik stretched it against the table, and let out a curt nod of approval. He began folding it, but before he put it away, a thought crossed his mind. He used to look great in a cloak, should he? No, certainly not, that would be unprofessional… Well, he would only know what his customer would see if he wore it as his customer would, right? It would actually be very professional of him to try it on.",
        "The sun was lower now; it was almost teatime, but he had to be professional.",
        "Rorik stood against a brass mirror, turning back and forth as he checked himself out. The cloak was fine, but he certainly looked like no hero. Though his limbs were slender, he had now accumulated a rather round belly in recent years. He was balding, and his remaining hair had silvered all the way. He did not even have a wizardly beard, as a mustache had always been his preference.",
        "*I am old.*",
        "Age was inevitable, but there was something else that bittered it.",
        "*I have failed.*",
        "*I am no champion, and the world does not remember me. My quests are unchronicled, and my stories unsung.*",
        "He took the cloak off, feeling ridiculous for having even tried it on. His glory days were gone, and though he always heard old people saying time flies by and life is fleeting, he had only now begun to feel hit with it.",
        "Life was fleeting indeed. It all went by so quickly.",
        "He tried to hold back the tears, but failed.",
        "*Some of my friends actually made it, and I was not outperformed by any of them. Was I just not lucky enough? I certainly had it back then… Did I not? Why were people not impressed with me? Am I… Is this… What is this smell?*",
        "*Lemon verbena?*",
        "The door of his study was suddenly opened. He quickly wiped away the tears and finished folding the cloak before turning to face the door. There stood Maeve, ceramic mug in hand, steaming as the citrus smell entered the room. Her curls were, too, taken by silver and white, though one day they had been very dark. Her skin was not as wrinkled as Rorik’s, but age had caught up to her as well. They were nearly the same age. Her smile, however, had not aged at all. She fixed her eyes with such amazement on Rorik that he suddenly felt as young as he had ever been. But then it hit him.",
        "*What is she doing wasting my lemon verbena? This is for special occasions.*",
        "He furrowed a brow and voiced his thoughts.",
        "“What is the special occasion?”",
        "It was not an inquiry, though he asked. He really meant to protest her choice of herbs, but she simply walked in his direction, mug steaming in her hand.",
        "She simply handed it over to him, eyes locked with his.",
        "“Ye watching the sunset with me.”",
        "She turned and as she walked towards the door, Maeve looked at him over her shoulder.",
        "Oh, the memories flooded his mind like a river. That thing she did, smiling over her shoulder, reminded him all at once of the day they met, the countless times she had gotten him into trouble, their wedding day, their children, then grandchildren, thousands of sunsets, and… well, today.",
        "Mayhaps he would not be remembered, but he was surely loved. He followed after her, walking past the gryphon’s beak, past the broken shield, and as he struggled against the descent of the last step, he turned his gaze to a charcoal drawing that was nailed to his wall. It was his granddaughter’s rendering of one of his stories. A human figure that was not very faithful in proportion held a blade not drawn straight against a hulking figure. The rudimentary nature of it was certainly excused, as it was drawn by a child. Perhaps Rorik was not unchronicled after all. In her eyes, that was the depiction of a hero. Her grandfather.",
        "The smell of lemon verbena rose to him once more as Maeve spoke through the window.",
        "“What’s the holdup?”",
        "The first sip of tea went in with warmth and comfort.",
        "He walked outside and saw the scene he had seen hundreds of times. The sun was setting over the fields in the West. Their home was on a slight hill above the others, so it gave them a view of the stone path that stretched to the end of the village, and then the fields and trees that rested against the setting sun.",
        "Maeve drank her tea, standing up as she usually did when she watched the sunset. Rorik stood a little further back as he had just walked outside. He drank the tea one more time, then lifted up his eyes to see Maeve’s curls in the light of the setting sun.",
        "He scratched his balding head and chuckled to himself. She did not need to turn around again for him to feel lucky. That woman who had walked by his side, loved him, bore his children, and now spoiled his grandchildren was his world.",
        "And the world remembers."
      ]
    },
    corpo: [
      { nota: "Agradecimentos a Renan Butkeraites, Italo Pacheco, Dhomini Martins, Yrwin Gomes e Rony pelas sugestões." },
      "Mais uma linha, mais um fio. As horas sumiam e os dias meio que se aglomeravam num só quando o Velho Rorik costurava. O giro constante da roca costumava lhe roubar a atenção. Deixava nele a sensação incômoda de que o tempo era… fugaz. Talvez a culpa nem fosse da roca, e sim da idade; o joelho ruim não o deixava manter o pedal em movimento por muito tempo. De qualquer forma, não era preciso muito para roubar a atenção do Velho Rorik. Não que a costura não merecesse atenção, mas era, por natureza, um ofício monótono. Era um trabalho tão bom quanto qualquer outro para um homem da sua idade, e o que rendia bastava para que ele e sua esposa vivessem com conforto. Naquela aldeia, pelo menos.",
      "Não era nenhum formigueiro de aventureiros. Não havia ali guilda de renome nem taverna das mais agitadas; o que havia, e de sobra, era gente de idade, como eles. A aldeia não ficava longe de uma das grandes cidades da província, e quase todo o comércio do lugar vinha dos aventureiros que apareciam atrás de serviço mais em conta. Não era assim que Rorik tinha imaginado a velhice. Ver pessoas indo e vindo, largando em suas mãos o que uma aventura estragara para logo levá-lo, remendado, à outra, enquanto ele próprio já não era capaz de grandes feitos.",
      "O velho suspirou. *Mais uma*, pensou, ao cortar o fio da roca e terminar de enrolá-lo no carretel. Olhou demoradamente para fora: a aldeia sossegada, meia dúzia de pessoas no caminho de pedra.",
      "*Já está na hora do chá?*",
      "Rorik era um entusiasta do chá, mas um entusiasta metódico, quase ritual. Permitia-se duas pausas por dia, todo santo dia, é claro. Uma, porém, era no desjejum, e a outra no fim da jornada, ao lado da esposa.",
      "Só que o sol ainda estava alto demais para dar o dia por encerrado.",
      "— Unghh — resmungou, esticando as costas.",
      "*Dá tempo para mais uma.*",
      "Estendeu a mão para uma capa dobrada sobre a bancada. Presa a ela por um alfinete havia um pedaço de pergaminho, com as instruções que ele mesmo deixara, mais cedo, sobre o que fazer com a encomenda.",
      "Leu o pergaminho; na própria letra, dizia: “Costurar com linha de linho encerada, a verde.” Assentiu de leve, lembrando-se enfim do motivo de ter passado a manhã fiando linho: aquela capa levaria o resto da sua linha verde.",
      "Era uma bela capa, de um verde-escuro, com adornos nas bordas, fechada no alto por um broche de bronze da guilda dos patrulheiros. Devia ser de algum recruta, no entanto, envergonhado demais para entregá-la ao intendente da própria guilda.",
      "— O que foi que aconteceu aqui? — sussurrou, desdobrando a capa e deixando-a pender das mãos. Achou o furo de imediato.",
      "Parecia obra de uma flecha que a atravessara de lado a lado. O velho examinou o estrago mais de perto; a impressão era que o dano foi causado por uma pedra pontiaguda, bruta, malfeita.",
      "*Goblins, com certeza.*",
      "Sorriu, imaginando exatamente como a coisa aconteceu. Era um jeito de arruinar uma capa perfeita. *Mas, pensando bem, antes uma capa furada do que uma flechada no joelho*, pensou, enquanto as mãos, por instinto, pousavam sobre o joelho direito. Grunhiu, espantando a ideia, e abriu uma das gavetas da mesa de costura. Remexeu um par de latinhas etiquetadas até a mão bater no fundo.",
      "Fechou a gaveta, irritado, e tentou outra. Nada.",
      "Aqueceu a garganta com um pigarro e então quebrou o silêncio da casa.",
      "— Maeve!",
      "Houve uma pequena demora, como se a esposa também tivesse pigarreado em algum outro canto da casa.",
      "— O quêêê? — berrou a voz lá de baixo.",
      "— Você viu a cera de abelha!?",
      "— A o quê!?",
      "Ele grunhiu e se levantou, indo devagar até a porta, mancando de leve. Escancarou-a e gritou de novo, voltado para a escada.",
      "— A cera de abelha!",
      "Um instante de silêncio.",
      "— Eu trouxe aqui pra baixo pra selar uma carta.",
      "Rorik bufou. Maeve sabia muito bem o que ele achava de ela pegar as coisas da oficina e não devolvê-las ao devido lugar.",
      "— E que tal trazer de volta, então!?",
      "A resposta veio ligeira.",
      "— Vem buscar você, seu folgado!",
      "Rorik soltou uma risada. Maeve sempre fora muito… intensa. Não pensava duas vezes antes de dizer o que lhe passava pela cabeça e, ainda assim, dava um jeito de ser cativante até mesmo na grosseria. Ele sabia que discutir seria gastar fôlego à toa; Maeve, afinal, era teimosa.",
      "De modo que começou a descida. Era uma jornada curta, embora mais custosa agora do que ele gostaria de admitir.",
      "*Quão desleixado alguém precisa ser para levar uma flechada de goblin?* Pensou, vencendo o primeiro degrau. *Eu jamais deixaria isso acontecer. Não no meu auge.* O joelho dolorido quase ousou discordar, mas ser atingido por um arqueiro élfico de uma seita sombria era outra história.",
      "Olhou para a direita, onde o bico de um grifo, preso a uma placa de madeira, pendia da parede da escada: troféu de jornadas de muitos anos atrás.",
      "Não pôde deixar de lembrar o dia em que ele e os companheiros abateram a fera. Ela vinha atacando uma aldeia nos confins do Leste, ameaçando mercadores e crianças. O grupo estava só de passagem quando ouviu os rumores e se ofereceu para ajudar.",
      "Rorik ainda se lembrava do muxoxo de desdém do chefe da aldeia quando disseram que dariam conta da criatura, e do espanto no rosto do mesmo quando voltaram, a passo tranquilo, com a cabeça dela. Ainda guardava uma ou duas cicatrizes daquele encontro. O sorriso, porém, logo murchou. Pois, quando retornou àquela aldeia uns meses depois, ninguém sabia quem ele era.",
      "Venceu a custo mais um degrau e relanceou o escudo quebrado que pendia, em dois pedaços, da parede à esquerda: outra de suas relíquias. Enfrentara sozinho um ogro descomunal e sobrevivera. Não sem cicatrizes, é claro, mas fora um duelo lendário. Ao menos na cabeça dele.",
      "Tampouco havia contos ou canções a respeito.",
      "O último degrau doeu mais que os anteriores, como se a emoção o tivesse deixado mais pesado a cada passo. Era essa a dor de Rorik. Sempre sonhara em se tornar um herói, como os das lendas e canções que ouvia quando menino. Mas ninguém se lembrava dele por nenhuma de suas aventuras. *Imagino que abater grifos não impressione tanto quanto matar dragões, nem duelar com ogros tanto quanto derrubar gigantes.* Outros haviam se tornado heróis no seu tempo; Rorik não fora um deles. Agora não passava de um alfaiate de aldeia. Arrastou um passo até a janela e conferiu o sol outra vez. Obviamente, o astro mal tivera tempo de descer desde a última olhada, de modo que ainda não era hora do chá. Nada além dos próprios hábitos o impedia de tomá-lo em outro horário, mas ele também era teimoso. Passou por um pedaço de pergaminho pregado à parede, um desenho a carvão feito pela neta, e não lhe deu atenção ao entrar na cozinha.",
      "Estava atrás da cera de abelha, mas foi como se os próprios pés o traíssem e o levassem à despensa. Só que ainda não era hora do chá. Deteve-se ali um momento, mesmo assim, admirando a sua coleção de ervas. Os aromas chegaram todos de uma vez, mas, depois de aspirá-los, ele soube distinguir a nota fresca de pinho do alecrim, o almíscar terroso da sálvia, o calor aromático do tomilho. Já ia dar as costas à despensa quando o olhar caiu sobre uma erva guardada num pote de vidro. Não resistiu. Pegou o pote e ergueu a tampa, e respirou fundo aquele frescor cítrico.",
      "*Cidrão.*",
      "Fechou os olhos, deliciado, como se o cheiro bastasse para aplacar um pouco a saudade do segundo chá. Guardou a erva. Aquela era só para ocasiões especiais, mais difícil de achar que as outras.",
      "E, antes que conseguisse se afastar da despensa e ir atrás da cera, uma mão suave tocou-lhe o ombro.",
      "A de Maeve.",
      "Trazia no rosto um sorriso franco, embora Rorik a conhecesse o bastante para saber que metade daquele sorriso era por tê-lo feito descer em vez de ela mesma subir. A outra metade dizia simplesmente “eu te amo”, sem precisar de palavras.",
      "Veja bem, essa tinha sido uma das coisas que fizeram Rorik se apaixonar por Maeve, lá atrás. Ou que ajudaram, melhor dizendo, pois ninguém se apaixona por um motivo só. O jeito como Maeve falava com os olhos, os lábios e os ombros, sem precisar dizer nada. Com as palavras ela era brincalhona, vivia chamando os amigos de nomes que alguns julgariam mal-educados e fazendo piadas que outros achariam ofensivas, mas a voz era sempre terna e os modos, gentis.",
      "Estendeu a mão com o tablete de cera, obrigando Rorik, ainda assim, a dar mais um passo para apanhá-lo.",
      "— Que que você tá fazendo? — perguntou ela, com o sotaque carregado.",
      "— Capa de patrulheiro. Flecha de goblin, aposto.",
      "Ele não se demorou; deu meia-volta e tomou outra vez o rumo da escada.",
      "— Flecha de goblin? — repetiu ela.",
      "Rorik só grunhiu que sim.",
      "— Desleixado — comentou ela, enquanto ele travava sua batalha com os degraus, um a um.",
      "Ele riu baixinho; tinha pensado o mesmo.",
      "— Nunca teria acontecido com você — acrescentou ela, num tom brando.",
      "Aquilo arrancou de Rorik um sorriso na mesma hora.",
      "— Pode apostar — disse, chegando ao topo.",
      "Soltou outro grunhido ao sentar-se para retomar o trabalho.",
      "Tirou do gancho a meada de linho verde e estendeu um pedaço da linha sobre a capa; a cor era quase idêntica. Um bom olho notaria a pequena diferença. Franziu a testa e seguiu em frente. Tinha certeza de que o intendente da guilda teria acertado o tom, mas o freguês patrulheiro escolhera um artesão mais simples, fosse pela vergonha, fosse pelo desconto.",
      "Aparou as bordas esgarçadas do furo e assentou por trás dele um retalho de lã verde. Depois correu a linha pelo tablete de cera, uma vez, duas, até senti-la firme e lisa entre os dedos, e enfiou-a na agulha na segunda tentativa, o que contou como uma pequena vitória. Não demorou a conferir o sol de novo; estava um pouco mais baixo, mas não o bastante.",
      "Então remendou o furo, pouco a pouco, fio a fio. Olhou pela janela para ver as horas mais uma vez. Um vizinho passou e acenou lá de baixo. Rorik tinha as mãos ocupadas, de modo que respondeu com um aceno de cabeça.",
      "Os pontos iam miúdos e cerrados, cada um apanhando a beira do rasgo e prendendo-a contra o remendo. Por baixo, por cima, puxa. Por baixo, por cima, puxa. No fim das contas, não era tão diferente da roca. As mãos sabiam o caminho, e a mente ficava livre para vagar por onde bem entendesse.",
      "A agulha atravessou o pano pela última vez. A capa estava remendada. Rorik a esticou sobre a mesa e aprovou com um aceno curto. Começou a dobrá-la, mas, antes de guardá-la, um pensamento lhe passou pela cabeça. Ele costumava ficar muito bem de capa. E se…? Não, de jeito nenhum, seria falta de profissionalismo… Bem, ele só saberia o que o freguês ia ver se a vestisse como o freguês a vestiria, certo? Experimentá-la seria, na verdade, muito profissional da parte dele.",
      "O sol já ia mais baixo; estava quase na hora do chá, mas era preciso ser profissional.",
      "Rorik postou-se diante do espelho de bronze, virando para um lado e para o outro. A capa era bonita, mas ele não parecia nada heróico. Os braços e as pernas continuavam finos, só que os últimos anos lhe haviam dado uma barriga bem redonda. Estava ficando calvo, e o cabelo que restava tinha embranquecido por inteiro. Nem barba de mago ele tinha, pois sempre preferira o bigode.",
      "*Estou velho.*",
      "Envelhecer era inevitável, mas havia outra coisa que tornava aquilo amargo.",
      "*Eu fracassei.*",
      "*Não sou campeão de nada, e o mundo não se lembra de mim. Ninguém registrou minhas jornadas, ninguém cantou minhas histórias.*",
      "Tirou a capa, sentindo-se ridículo por tê-la sequer experimentado. Seus dias de glória tinham ficado para trás e, embora sempre ouvisse os mais velhos dizerem que o tempo voa e a vida é breve, só agora começava a sentir o golpe.",
      "A vida era breve, de fato. Tudo tinha passado tão depressa.",
      "Tentou segurar as lágrimas, e não conseguiu.",
      "*Alguns dos meus amigos chegaram lá, e nenhum deles era mais hábil do que eu. Será que só me faltou sorte? Eu tinha o que era preciso naquele tempo… Não tinha? Por que ninguém se impressionava comigo? Será que eu… Será que isto… Que cheiro é esse?*",
      "*Cidrão?*",
      "A porta da oficina se abriu de repente. Ele enxugou depressa as lágrimas e terminou de dobrar a capa antes de se virar. Lá estava Maeve, caneca de cerâmica na mão, fumegante, o aroma cítrico invadindo o cômodo. Também os cachos dela tinham sido tomados pelo prateado e pelo branco, embora um dia tivessem sido bem escuros. A pele não era tão enrugada quanto a de Rorik, mas a idade a alcançara do mesmo jeito. Tinham quase a mesma idade. O sorriso, porém, não envelhecera nada. Ela pousou nele uns olhos tão maravilhados que, de repente, Rorik se sentiu tão jovem quanto já fora um dia. Mas então a ficha caiu.",
      "*O que ela está fazendo, gastando o meu cidrão? Isso é para ocasiões especiais.*",
      "Franziu o cenho e deu voz ao pensamento.",
      "— Qual é a ocasião especial?",
      "Não era bem uma pergunta, embora viesse em forma de uma. O que ele queria mesmo era protestar contra a escolha da erva, mas ela apenas veio em sua direção, a caneca soltando vapor.",
      "Entregou-a sem mais, os olhos presos aos dele.",
      "— Você vai ver o pôr do sol comigo.",
      "Virou-se e, a caminho da porta, olhou para ele por cima do ombro.",
      "Ah, as lembranças inundaram-lhe a mente como um rio. Aquele gesto dela, o sorriso por cima do ombro, trouxe-lhe de uma só vez o dia em que se conheceram, as incontáveis encrencas em que ela o metera, o casamento, os filhos, depois os netos, milhares de pores do sol e… bem, o dia de hoje.",
      "Talvez jamais fosse lembrado, mas ele certamente era amado, e disso não havia dúvida. Foi atrás dela, passando pelo bico do grifo, pelo escudo quebrado, e, enquanto penava para vencer o último degrau, voltou os olhos para um desenho a carvão pregado à parede. Era a versão da neta para uma de suas histórias. Uma figura humana de proporções não muito fiéis empunhava uma espada de traço torto contra um vulto enorme. A rudeza do desenho estava mais que perdoada, pois era obra de criança. Talvez as jornadas de Rorik não tivessem ficado sem registro, afinal. Aos olhos dela, aquele era o retrato de um herói. O avô.",
      "O cheiro de cidrão subiu até ele mais uma vez quando Maeve falou pela janela.",
      "— Tá esperando o quê?",
      "O primeiro gole de chá desceu morno e reconfortante.",
      "Ele saiu e viu a cena que já tinha visto centenas de vezes. O sol se punha sobre os campos do Oeste. A casa ficava numa leve colina, acima das outras, e dali se avistava o caminho de pedra que se estendia até o fim da aldeia, e depois os campos e as árvores recostados no poente.",
      "Maeve bebia seu chá de pé, como sempre fazia ao ver o pôr do sol. Rorik ficou um pouco mais atrás, recém-saído de casa. Tomou mais um gole e então ergueu os olhos para os cachos de Maeve, acesos pela luz do fim da tarde.",
      "Coçou a cabeça calva e riu sozinho. Ela nem precisava se virar de novo para que ele se sentisse um homem de sorte. Aquela mulher, que caminhara ao seu lado, que o amara, que lhe dera filhos e que agora mimava os seus netos, era o seu mundo.",
      "E o mundo se lembra."
    ]
  },
  {
    slug: "a-sombra-ofuscada",
    titulo: "A Sombra Ofuscada",
    resumo: "Minhas reflexões sobre a Obra Clássica de Tanizaki",
    data: "2026-07-05",
    autor: "Israel Subira",
    corpo: [
      "Em fuga das inconveniências os ocidentais não enxergaram a beleza que existia em alguma delas. Esse é o coração do clássico, que discorre em grande parte porque o Japão é como é.",
      { imagem: "assets/artigos/em-louvor-da-sombra.png", legenda: "Em louvor da sombra, de Jun’ichirō Tanizaki (Penguin Companhia).", tamanho: "pequena" },
      "Tanizaki se pergunta como seria o desenvolvimento tecnológico se o mesmo pudesse ser isolado culturalmente, ao invés de importado de diferentes países que avançaram suas tecnologias. Quando isso acontece, é quase inevitável que a roupagem cultural dessa tecnologia seja importada também. Mas se ela fosse desenvolvida sem “emprestar” de outras culturas seriam diferentes. Como brasileiro, não pude deixar de pensar em Drummond ou em Araripe. Países estrangeiros rapidamente \"emprestaram” desses avanços e pouco mencionam o Brasil.",
      "Tanizaki passou pelo choque de perceber a dificuldade de se acomodar a beleza tradicional do Japão com a crescente demanda pela conveniência. E de repente, hotéis e restaurantes estavam precisando implementar recursos como luzes elétricas e ventiladores em ambientes que não haviam sido desenhados para isso.",
      { imagem: "assets/artigos/tanizaki.png", legenda: "Jun’ichirō Tanizaki.", tamanho: "pequena" },
      "Talvez minha mente seja ocidental (ou moderna) demais pra me apegar a beleza rústica de “aliviar o ventre” num vaso de madeira, no escuro ou olhando pro mato. Mas eu certamente consigo perceber a beleza de um jantar à luz de velas. Enquanto eu mesmo aprecio a conveniência de um ar condicionado, também aprecio a resiliência climática que se desenvolve sem o mesmo (Mas vivo com ar condicionado).",
      { imagem: "assets/artigos/banheiro-nishigawara.png", legenda: "Banheiro público no Parque Nishigawara, em Ibaraki. Foto: garycycles, CC BY 2.0." },
      "Mas o maior contraste entre ocidente e oriente que percebi na leitura, foi que parte do mundo se livrou de coisas inconvenientes sem olhar pra trás. Enquanto o japão se apegou a beleza que existia nas mesmas. Sem necessariamente demonizar a conveniência em si, mas a maneira como ela foi disruptiva no desenvolvimento cultural. Até porque todo mundo aprecia algum tipo de progresso ou conveniência, enquanto certamente rejeita outros (como o próprio autor que se rendeu a modernidades em seu próprio lar).",
      { imagem: "assets/artigos/ceramica-na-sombra.png", legenda: "", tamanho: "pequena" },
      "O ponto, é que nem tudo na vida é pra ser conveniente, talvez IA seja um bom exemplo disso, buscamos conveniência ao custo de beleza. Numa tentativa de otimizar tudo estão colocando inteligência artificial até em microondas e outros utensílios domésticos. Mas ao mesmo tempo, tudo parece ter muito menos “alma” do que antigamente.",
      "O próprio microondas já é algo a ser discutido, Não consigo convencer minha esposa a usar um de jeito nenhum, ela insiste sempre em sua frigideira de ferro. Eu as vezes queria fugir da inconveniência da limpeza, mas um dia descobrimos no médico que o ferro da Priscilla estava altíssimo, em grande parte devido ao seu uso da bendita frigideira. Sem falar que uma frigideira de ferro é muito mais bonita do que uma caixinha de alumínio (ou branco hospitalar), especialmente quando elas tem aquela vibe mineira.",
      "Mas assim é o ocidente, grandes estacionamentos pouco arborizados, centrais de ar condicionado constantemente “cantando” porque o dia está quente demais, cabos por toda parte e robôs se alimentando das minhas peculiaridades pra me inundar com anúncios e me vender mais conveniência. Talvez o Tanizaki tenha razão.",
      "Pense na nova ferrari elétrica que parece um iphone. Bons e velhos italianos quase derrubaram seus espressos no chão. Algumas coisas já encontraram sua melhor versão no passado, e merecem ser conservadas. Enquanto veículos híbridos ou elétricos tem sua proposta interessante, nada bate uma Ford f100 de 1972, de cabine única, na minha opinião. Por que? Por que hoje se pensa em conveniência, mas antigamente se pensava em beleza.",
      "O que já me leva pra mais um ponto, o carro não era uma fuga da inconveniência em si? Todo crítico de conveniências as critica convenientemente. Não deveríamos então estar andando de cavalo por aí? Todo progresso tecnológico terá seus lovers e haters. O progresso é inevitável, a resistência é opcional.",
      "Você é (mais ou menos) livre pra andar de cavalo. Pra não usar IA e escrever texto com errinhos, sem trações ou tríades (e quem gostava de usá-los antes agora tem medo, como eu que acabei de os substituir por parêntesis nesse momento) E também pode optar por rusticidade quando outros focam em tecnologia.",
      "Não quero que IA escreva por mim, nem que lave minhas louças, mas não me oponho a ela quando integrada a um aplicativo de rastrear calorias e macros, o que facilita bastante a vida. Seria eu um hipócrita então? Seletivo, no mínimo. Não sou contra o progresso tecnológico, mas sou contra a desistência da arte.",
      "Outra coisa, Tanizaki disse que ouviu idosos se queixando que cuidaram de seus pais quando eles eram mais velhos, mas agora que eles mesmos haviam alcançado idade avançada, a nova geração via idosos como “imundos”.",
      "Isso me doeu, outro dia ouvi um senhor se queixando durante o almoço, embora num tom de brincadeira: “nunca comi a maior coxa de frango” ele procedeu a explicar que quando era criança, a maior coxa pertencia ao pai, e quando adulto, era feio não dar a maior para as crianças. A mesa irrompeu em risada, e pouco foi discutido sobre o assunto. Eu não consegui parar de pensar naquilo. Embora em tom de brincadeira, aquele homem não sentia o respeito que ele mesmo entregou. Embora seus filhos possivelmente se sentissem mais próximos dele do que ele se sentira de seus pais.",
      "Quando eu e minha esposa morávamos em Oklahoma, fizemos algumas visitas em asilos, onde gastamos tempo jogando jogos de tabuleiro, jogando conversa fora e cantando velhas canções com os idosos da nossa região. Escutamos incríveis historias de vida e passamos tempo com pessoas cativantes, mas que sempre nos agradeciam por ter passado ali especialmente por se sentirem esquecidos por suas famílias.",
      "E o que isso tem a ver com avanço tecnológico e a fuga das inconveniências? Penso que tudo isso se conecta em saber ter olhos que constantemente buscam beleza. Na pele suada e na latrina escura, nos avanços tecnológicos e nas pessoas esquecidas.",
      "Humanos são preciosos e belos, por isso as obras de suas mãos são inerentemente preciosas e belas também. No fim do dia, esse livro não é sobre o saudosismo do passado. Ele é sobre não se perder no futuro."
    ]
  }
];
